[sources.rabbitmq]
type = "rabbitmq"
host = "localhost"
port = 5672
vhost = "/"

[sources.rabbitmq.auth]
login = "guest"
password = "guest"

[sinks.console]
type = "console"
inputs = ["rabbitmq"]

[sinks.console.encoding]
codec = "json"
